# Generated by Django 6.1.1 on 2026-09-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('aggie_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PersonaTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(help_text='Ex: Estudante de Direito', max_length=100)),
                ('description', models.TextField(help_text="Instrução para a IA. Ex: 'Você estuda Direito, então use termos jurídicos às vezes.'")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(default='feliz', help_text='feliz, brava, com fome, dormindo', max_length=50)),
                ('energy', models.IntegerField(default=100)),
                ('back_pain_level', models.IntegerField(default=0, help_text='0 a 100 de dor na coluna')),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_text', models.CharField(max_length=255)),
                ('context_trigger', models.CharField(blank=True, help_text='Em qual momento usar (opcional)', max_length=50, null=True)),
            ],
        ),
    ]
