# Generated by Django 5.2.8 on 2026-09-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstate',
            name='affection',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='petstate',
            name='anger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petstate',
            name='boredom',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='petstate',
            name='hunger',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='memorycontext',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personatrait',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scriptedphrase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
