# Generated by Django 5.2.8 on 2026-09-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0002_petstate_affection_petstate_anger_petstate_boredom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstate',
            name='active_accessory',
            field=models.CharField(blank=True, help_text='ID do acessório equipado (ex: DETECTIVE_HAT)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petstate',
            name='hunger',
            field=models.IntegerField(default=80),
        ),
    ]
