# Generated by Django 5.2.8 on 2026-09-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0003_petstate_active_accessory_alter_petstate_hunger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptedphrase',
            name='context_trigger',
            field=models.CharField(blank=True, choices=[('HUNGRY', 'Fome (HUNGRY)'), ('LOW_ENERGY', 'Cansaço / Sono (LOW_ENERGY)'), ('BORED', 'Tédio (BORED)'), ('NEGATIVE', 'Dor/TPM/Triste (NEGATIVE)'), ('RANDOM', 'Aleatório / Lore (RANDOM)')], help_text='Em qual momento usar (opcional)', max_length=50, null=True),
        ),
    ]
