# Generated by Django 5.2.8 on 2026-09-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0004_alter_scriptedphrase_context_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personatrait',
            options={'ordering': ['id'], 'verbose_name': 'Persona Trait (contexto da IA)', 'verbose_name_plural': 'Persona Traits (contexto da IA)'},
        ),
        migrations.AlterField(
            model_name='personatrait',
            name='description',
            field=models.TextField(help_text='Instrução completa enviada à IA em TODA mensagem. Escreva como regra de personagem.'),
        ),
        migrations.AlterField(
            model_name='personatrait',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Só traits ativos entram no contexto do chat.'),
        ),
        migrations.AlterField(
            model_name='personatrait',
            name='trait_name',
            field=models.CharField(help_text='Rótulo curto (ex: Dona, Humor, Comida). Aparece no prompt da IA.', max_length=100),
        ),
    ]
