# Generated by Django 5.2.8 on 2026-09-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0005_alter_personatrait_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptedphrase',
            name='context_trigger',
            field=models.CharField(blank=True, choices=[('HUNGRY', 'Fome (HUNGRY)'), ('LOW_ENERGY', 'Cansaço / Sono (LOW_ENERGY)'), ('BORED', 'Tédio (BORED)'), ('NEGATIVE', 'Dor/TPM/Triste (NEGATIVE)'), ('RANDOM', 'Aleatório / Lore (RANDOM)'), ('ACTION_PET', 'Ao receber carinho (ACTION_PET)'), ('ACTION_EAT', 'Ao ser alimentada (ACTION_EAT)'), ('ACTION_WAKE', 'Ao acordar (ACTION_WAKE)'), ('ACTION_SLEEP', 'Ao ir dormir (ACTION_SLEEP)'), ('ACTION_ZOOMIES', 'Ao entrar em modo turbo (ACTION_ZOOMIES)')], help_text='Em qual momento usar (opcional)', max_length=50, null=True),
        ),
    ]
