# Generated by Django 5.2.8 on 2026-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0007_alter_scriptedphrase_context_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThoughtRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='Nome da regra (ex: Fome Crítica)', max_length=100)),
                ('context_trigger', models.CharField(choices=[('HUNGRY', 'Fome (HUNGRY)'), ('LOW_ENERGY', 'Cansaço / Sono (LOW_ENERGY)'), ('BORED', 'Tédio (BORED)'), ('NEGATIVE', 'Dor/TPM/Triste (NEGATIVE)'), ('RANDOM', 'Aleatório / Lore (RANDOM)'), ('ACTION_PET', 'Ao receber carinho (ACTION_PET)'), ('ACTION_EAT', 'Ao ser alimentada (ACTION_EAT)'), ('ACTION_WAKE', 'Ao acordar (ACTION_WAKE)'), ('ACTION_SLEEP', 'Ao ir dormir (ACTION_SLEEP)'), ('ACTION_ZOOMIES', 'Ao entrar em modo turbo (ACTION_ZOOMIES)'), ('TAB_RETURN', 'Ao voltar para a aba do navegador (TAB_RETURN)')], help_text='Qual contexto essa regra ativa?', max_length=50)),
                ('condition_field', models.CharField(choices=[('hunger', 'Fome'), ('energy', 'Energia'), ('boredom', 'Tédio'), ('anger', 'Raiva'), ('back_pain_level', 'Dor na Coluna'), ('mood', 'Humor')], max_length=50)),
                ('condition_operator', models.CharField(choices=[('<', 'Menor que (<)'), ('>', 'Maior que (>)'), ('==', 'Igual a (==)'), ('in', 'Contém na lista separada por vírgula (in)')], max_length=5)),
                ('condition_value', models.CharField(help_text="Valor para comparar (ex: 40, ou 'brava,triste' se usar 'in')", max_length=100)),
                ('priority', models.IntegerField(default=10, help_text='Prioridade da regra. Maior = avaliada primeiro.')),
                ('activation_chance', models.FloatField(default=1.0, help_text='Chance de 0.0 a 1.0 de ativar caso a condição seja verdadeira.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regra de Pensamento (Thought Rule)',
                'verbose_name_plural': 'Regras de Pensamento (Thought Rules)',
                'ordering': ['-priority'],
            },
        ),
    ]
