# Generated by Django 5.2.8 on 2026-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(help_text='Ex: WALK, ZOOMIES, IDLE', max_length=50, unique=True)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Peso no sorteio. Ex: 40 para comum, 1 para raro.')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, o peso será tratado como 0 (nunca sorteado).')),
            ],
            options={
                'verbose_name': 'Action Probability',
                'verbose_name_plural': 'Action Probabilities',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='AggiePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Ex: TAIL_CHASE, FOME, ZOOMIES', max_length=50)),
                ('text', models.CharField(help_text='O que a gata vai falar', max_length=255)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Peso no sorteio das frases.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aggie Phrase',
                'verbose_name_plural': 'Aggie Phrases',
                'ordering': ['category', '-weight'],
            },
        ),
    ]
