# Generated by Django 5.2.8 on 2026-09-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Chave da configuração (ex: GROOM_STOP_CHANCE)', max_length=50, unique=True)),
                ('value', models.FloatField(default=0.5, help_text='Valor numérico (ex: 0.6 para 60%)')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Brain Setting (Pacing)',
                'verbose_name_plural': 'Brain Settings (Pacing)',
                'ordering': ['key'],
            },
        ),
    ]
