# Generated by Django 5.2.8 on 2026-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_brainsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do evento (ex: Evento Matrix)', max_length=50, unique=True)),
                ('keywords', models.CharField(help_text='Palavras-chave separadas por vírgula (ex: matrix,hack,frio)', max_length=255)),
                ('event_type', models.CharField(help_text='Tipo de evento a disparar (ex: MATRIX, DETECTIVE, BIRTHDAY, FEED, STARTLE)', max_length=50)),
                ('reply_text', models.CharField(blank=True, help_text='Frase opcional para a gata falar quando disparar', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chat Command (Event)',
                'verbose_name_plural': 'Chat Commands (Events)',
                'ordering': ['name'],
            },
        ),
    ]
