# Generated by Django 5.2.8 on 2026-09-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_chatcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionprobability',
            name='action_name',
            field=models.CharField(choices=[('WALK', 'Andar (WALK)'), ('RUN', 'Correr (RUN)'), ('IDLE', 'Parada (IDLE)'), ('SIT_LOAF', 'Deitar pãozinho (SIT_LOAF)'), ('GROOM', 'Lamber-se (GROOM)'), ('SIT', 'Sentar (SIT)'), ('JUMP', 'Pular (JUMP)'), ('TAIL_CHASE', 'Perseguir o rabo (TAIL_CHASE)'), ('ZOOMIES', 'Zoomies (Corrida Maluca)'), ('HUNTING', 'Caçando (HUNTING)'), ('WAKE_UP', 'Acordar (WAKE_UP)'), ('AMBUSH', 'Emboscada (AMBUSH)'), ('BUG_CATCH', 'Caçar Inseto (BUG_CATCH)'), ('FOME', 'Reclamação de Fome (FOME)')], help_text='Nome da ação no frontend', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='actionprobability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actionprobability',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Peso da probabilidade (quanto maior, mais frequente)'),
        ),
        migrations.AlterField(
            model_name='aggiephrase',
            name='category',
            field=models.CharField(choices=[('WALK', 'Andar (WALK)'), ('RUN', 'Correr (RUN)'), ('IDLE', 'Parada (IDLE)'), ('SIT_LOAF', 'Deitar pãozinho (SIT_LOAF)'), ('GROOM', 'Lamber-se (GROOM)'), ('SIT', 'Sentar (SIT)'), ('JUMP', 'Pular (JUMP)'), ('TAIL_CHASE', 'Perseguir o rabo (TAIL_CHASE)'), ('ZOOMIES', 'Zoomies (Corrida Maluca)'), ('HUNTING', 'Caçando (HUNTING)'), ('WAKE_UP', 'Acordar (WAKE_UP)'), ('AMBUSH', 'Emboscada (AMBUSH)'), ('BUG_CATCH', 'Caçar Inseto (BUG_CATCH)'), ('FOME', 'Reclamação de Fome (FOME)')], help_text='Categoria/Ação onde a frase pode ser dita (ex: TAIL_CHASE)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aggiephrase',
            name='text',
            field=models.CharField(help_text='A frase que a gata vai falar', max_length=255),
        ),
        migrations.AlterField(
            model_name='aggiephrase',
            name='weight',
            field=models.FloatField(default=10.0, help_text='Chances de escolher esta frase (se houver mais de uma na categoria)'),
        ),
        migrations.AlterField(
            model_name='chatcommand',
            name='event_type',
            field=models.CharField(choices=[('MATRIX', 'Matrix (Hack)'), ('DETECTIVE', 'Detetive (Investigar)'), ('BIRTHDAY', 'Festa de Aniversário'), ('STARTLE', 'Susto (!)'), ('FEED', 'Alimentar (Comida/Sachê)'), ('LORE_CREATOR', 'Lore: Criador'), ('LORE_AGATHA', 'Lore: Agatha')], help_text='Tipo de evento a disparar', max_length=50),
        ),
    ]
