# Generated by Django 5.2.8 on 2026-09-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_alter_actionprobability_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainsetting',
            name='key',
            field=models.CharField(choices=[('GROOM_STOP_CHANCE', 'Chance de parar de lamber (GROOM)'), ('SIT_STOP_CHANCE', 'Chance de levantar (SIT)'), ('STATE_CHANGE_CHANCE', 'Impaciência: Mudar estado (IDLE/WALK)')], help_text='Chave da configuração de Pacing', max_length=50, unique=True),
        ),
    ]
