# Generated by Django 5.2.8 on 2026-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_alter_brainsetting_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionprobability',
            name='action_name',
            field=models.CharField(choices=[('WALK', 'Andar (WALK)'), ('RUN', 'Correr (RUN)'), ('IDLE', 'Parada (IDLE)'), ('SIT_LOAF', 'Deitar pãozinho (SIT_LOAF)'), ('GROOM', 'Lamber-se (GROOM)'), ('SIT', 'Sentar (SIT)'), ('JUMP', 'Pular (JUMP)'), ('TAIL_CHASE', 'Perseguir o rabo (TAIL_CHASE)'), ('ZOOMIES', 'Zoomies (Corrida Maluca)'), ('HUNTING', 'Caçando (HUNTING)'), ('WAKE_UP', 'Acordar (WAKE_UP)'), ('AMBUSH', 'Emboscada (AMBUSH)'), ('BUG_CATCH', 'Caçar Inseto (BUG_CATCH)'), ('YAWN', 'Bocejar (YAWN)'), ('SCRATCH', 'Coçar a Orelha (SCRATCH)'), ('FOME', 'Reclamação de Fome (FOME)')], help_text='Nome da ação no frontend', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='aggiephrase',
            name='category',
            field=models.CharField(choices=[('WALK', 'Andar (WALK)'), ('RUN', 'Correr (RUN)'), ('IDLE', 'Parada (IDLE)'), ('SIT_LOAF', 'Deitar pãozinho (SIT_LOAF)'), ('GROOM', 'Lamber-se (GROOM)'), ('SIT', 'Sentar (SIT)'), ('JUMP', 'Pular (JUMP)'), ('TAIL_CHASE', 'Perseguir o rabo (TAIL_CHASE)'), ('ZOOMIES', 'Zoomies (Corrida Maluca)'), ('HUNTING', 'Caçando (HUNTING)'), ('WAKE_UP', 'Acordar (WAKE_UP)'), ('AMBUSH', 'Emboscada (AMBUSH)'), ('BUG_CATCH', 'Caçar Inseto (BUG_CATCH)'), ('YAWN', 'Bocejar (YAWN)'), ('SCRATCH', 'Coçar a Orelha (SCRATCH)'), ('FOME', 'Reclamação de Fome (FOME)')], help_text='Categoria/Ação onde a frase pode ser dita (ex: TAIL_CHASE)', max_length=50),
        ),
    ]
