# Generated by Django 5.2.8 on 2026-09-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_alter_actionprobability_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainsetting',
            name='key',
            field=models.CharField(choices=[('GROOM_STOP_CHANCE', 'Chance de parar de lamber (GROOM)'), ('SIT_STOP_CHANCE', 'Chance de levantar (SIT)'), ('STATE_CHANGE_CHANCE', 'Impaciência: Mudar estado (IDLE/WALK)'), ('WANDER_INTERVAL_MS', 'Intervalo de pensamento (Wander AI em ms)'), ('RUN_MOVE_TIME_MS', 'Tempo correndo na ação RUN (ms)'), ('WALK_MOVE_TIME_MS', 'Tempo andando na ação WALK (ms)')], help_text='Chave da configuração de Pacing', max_length=50, unique=True),
        ),
    ]
