# Generated by Django 5.2.8 on 2026-09-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0008_alter_brainsetting_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcommand',
            name='event_type',
            field=models.CharField(choices=[('MATRIX', 'Matrix (Hack)'), ('DETECTIVE', 'Detetive (Investigar)'), ('BIRTHDAY', 'Festa de Aniversário'), ('STARTLE', 'Susto (!)'), ('FEED', 'Alimentar (Comida/Sachê)'), ('LORE_CREATOR', 'Lore: Criador'), ('LORE_AGATHA', 'Lore: Agatha'), ('CLOTHING_PARTY_HAT', 'Roupa: Chapéu de Festa'), ('CLOTHING_BOWTIE', 'Roupa: Gravata Borboleta'), ('CLOTHING_COLLAR', 'Roupa: Colar'), ('CLOTHING_SUNGLASSES', 'Roupa: Óculos de Sol'), ('CLOTHING_SCARF', 'Roupa: Cachecol'), ('CLOTHING_NONE', 'Roupa: Remover Acessório')], help_text='Tipo de evento a disparar', max_length=50),
        ),
    ]
