# Generated by Django 5.2.8 on 2026-09-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0009_alter_chatcommand_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcommand',
            name='event_type',
            field=models.CharField(choices=[('MATRIX', 'Matrix (Hack)'), ('DETECTIVE', 'Detetive (Investigar)'), ('BIRTHDAY', 'Festa de Aniversário'), ('STARTLE', 'Susto (!)'), ('FEED', 'Alimentar (Comida/Sachê)'), ('LORE_CREATOR', 'Lore: Criador'), ('LORE_AGATHA', 'Lore: Agatha'), ('LORE_RISOTO', 'Lore: Risoto de Camarão'), ('LORE_DIREITO', 'Lore: Direito / Vade Mecum'), ('LORE_BOLO', 'Lore: Bolo de Cenoura'), ('LORE_SONO', 'Lore: Sono / Coluna'), ('LORE_SERIES', 'Lore: Séries / Filmes'), ('LORE_MUSICA', 'Lore: Música / Cantoria'), ('LORE_AMOR', 'Lore: Amor / Presente'), ('CLOTHING_PARTY_HAT', 'Roupa: Chapéu de Festa'), ('CLOTHING_BOWTIE', 'Roupa: Gravata Borboleta'), ('CLOTHING_COLLAR', 'Roupa: Colar'), ('CLOTHING_SUNGLASSES', 'Roupa: Óculos de Sol'), ('CLOTHING_SCARF', 'Roupa: Cachecol'), ('CLOTHING_NONE', 'Roupa: Remover Acessório')], help_text='Tipo de evento a disparar', max_length=50),
        ),
    ]
