# Generated by Django 5.2.8 on 2026-09-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0010_alter_chatcommand_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcommand',
            name='reply_text',
            field=models.TextField(blank=True, help_text='Frase opcional. Para múltiplas variações, separe-as por |'),
        ),
    ]
